# Generated by Django 6.1 on 2026-08-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_doctor_id_alter_gallery_id'),
        ('myapp', '0004_faqcategory_faq'),
    ]

    operations = [
    ]
