# Generated by Django 6.1 on 2026-09-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_medicine_patient_treatment_bill_billitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_code',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='description',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.medicine'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.treatment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='op_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
