# Generated by Django 5.2.8 on 2026-09-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_opregistration'),
        ('myapp', '0008_alter_bill_options_alter_billitem_options_and_more'),
    ]

    operations = [
    ]
