# Generated by Django 5.2.8 on 2026-09-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20260908_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='opregistration',
            name='op_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='op_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.opregistration'),
        ),
        migrations.AlterField(
            model_name='opregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
