# Generated by Django 6.1 on 2026-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20260907_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
