# Generated by Django 6.1 on 2026-09-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_opregistration_id'),
        ('myapp', '0010_opregistration_op_number_patient_op_registration_and_more'),
    ]

    operations = [
    ]
