# Generated by Django 6.1 on 2026-09-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20260909_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='op_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='myapp.opregistration'),
        ),
    ]
