# Generated by Django 6.1 on 2026-09-22 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_patient_op_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='opregistration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='allergy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='allergy_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='arthritis',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='arthritis_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='asthma',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='asthma_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='cancer_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='date_of_discharge',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='diabetes_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='high_bp',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='high_bp_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='history_past_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='history_present_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='ip_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='presenting_complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='room_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opregistration',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
