# Generated by Django 5.2.8 on 2026-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_opregistration_address_opregistration_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Doctor diagnosis at billing time'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='UPI Transaction ID / Card Ref No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription_notes',
            field=models.TextField(blank=True, help_text='Medicine instructions'),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
